stages:
  - build

.build: &build
  stage: build
  script: 
    - cd docs
    - pip install -r requirements.txt
    - make html
  artifacts:
    paths:
      - docs/build/html

build:docker:
  <<: *build
  image: sphinxdoc/sphinx
  needs: [ ]
