[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "nsl-readthedocs"
authors = [{name = "Valerio Formato", email = "valerio.formato@cern.ch"}]
dynamic = ["version", "description"]
